// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Data;

#nullable disable

namespace SchoolManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260113070543_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagement.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Principal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Elm Street, City",
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4072),
                            Name = "Greenwood High School 1",
                            Principal = "Principal 1",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4208)
                        },
                        new
                        {
                            Id = 2,
                            Address = "2 Elm Street, City",
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4322),
                            Name = "Greenwood High School 2",
                            Principal = "Principal 2",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4322)
                        },
                        new
                        {
                            Id = 3,
                            Address = "3 Elm Street, City",
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4325),
                            Name = "Greenwood High School 3",
                            Principal = "Principal 3",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4325)
                        },
                        new
                        {
                            Id = 4,
                            Address = "4 Elm Street, City",
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4326),
                            Name = "Greenwood High School 4",
                            Principal = "Principal 4",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4327)
                        },
                        new
                        {
                            Id = 5,
                            Address = "5 Elm Street, City",
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4336),
                            Name = "Greenwood High School 5",
                            Principal = "Principal 5",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4336)
                        },
                        new
                        {
                            Id = 6,
                            Address = "6 Elm Street, City",
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4340),
                            Name = "Greenwood High School 6",
                            Principal = "Principal 6",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4340)
                        },
                        new
                        {
                            Id = 7,
                            Address = "7 Elm Street, City",
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4342),
                            Name = "Greenwood High School 7",
                            Principal = "Principal 7",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4342)
                        },
                        new
                        {
                            Id = 8,
                            Address = "8 Elm Street, City",
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4343),
                            Name = "Greenwood High School 8",
                            Principal = "Principal 8",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4344)
                        },
                        new
                        {
                            Id = 9,
                            Address = "9 Elm Street, City",
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4345),
                            Name = "Greenwood High School 9",
                            Principal = "Principal 9",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4345)
                        },
                        new
                        {
                            Id = 10,
                            Address = "10 Elm Street, City",
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4350),
                            Name = "Greenwood High School 10",
                            Principal = "Principal 10",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 278, DateTimeKind.Utc).AddTicks(4351)
                        });
                });

            modelBuilder.Entity("SchoolManagement.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(3897),
                            Email = "student1@example.com",
                            FullName = "Student 1 Fullname",
                            Phone = "0977000101",
                            SchoolId = 2,
                            StudentId = "S00001",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4055)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4220),
                            Email = "student2@example.com",
                            FullName = "Student 2 Fullname",
                            Phone = "0977000102",
                            SchoolId = 3,
                            StudentId = "S00002",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4220)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4225),
                            Email = "student3@example.com",
                            FullName = "Student 3 Fullname",
                            SchoolId = 4,
                            StudentId = "S00003",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4226)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4229),
                            Email = "student4@example.com",
                            FullName = "Student 4 Fullname",
                            Phone = "0977000104",
                            SchoolId = 5,
                            StudentId = "S00004",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4229)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4231),
                            Email = "student5@example.com",
                            FullName = "Student 5 Fullname",
                            Phone = "0977000105",
                            SchoolId = 6,
                            StudentId = "S00005",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4232)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4237),
                            Email = "student6@example.com",
                            FullName = "Student 6 Fullname",
                            SchoolId = 7,
                            StudentId = "S00006",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4237)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4240),
                            Email = "student7@example.com",
                            FullName = "Student 7 Fullname",
                            Phone = "0977000107",
                            SchoolId = 8,
                            StudentId = "S00007",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4240)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4242),
                            Email = "student8@example.com",
                            FullName = "Student 8 Fullname",
                            Phone = "0977000108",
                            SchoolId = 9,
                            StudentId = "S00008",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4243)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4245),
                            Email = "student9@example.com",
                            FullName = "Student 9 Fullname",
                            SchoolId = 10,
                            StudentId = "S00009",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4245)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4249),
                            Email = "student10@example.com",
                            FullName = "Student 10 Fullname",
                            Phone = "0977000110",
                            SchoolId = 1,
                            StudentId = "S00010",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4249)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4252),
                            Email = "student11@example.com",
                            FullName = "Student 11 Fullname",
                            Phone = "0977000111",
                            SchoolId = 2,
                            StudentId = "S00011",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4252)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4254),
                            Email = "student12@example.com",
                            FullName = "Student 12 Fullname",
                            SchoolId = 3,
                            StudentId = "S00012",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4254)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4258),
                            Email = "student13@example.com",
                            FullName = "Student 13 Fullname",
                            Phone = "0977000113",
                            SchoolId = 4,
                            StudentId = "S00013",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4258)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4260),
                            Email = "student14@example.com",
                            FullName = "Student 14 Fullname",
                            Phone = "0977000114",
                            SchoolId = 5,
                            StudentId = "S00014",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4261)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4263),
                            Email = "student15@example.com",
                            FullName = "Student 15 Fullname",
                            SchoolId = 6,
                            StudentId = "S00015",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4263)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4265),
                            Email = "student16@example.com",
                            FullName = "Student 16 Fullname",
                            Phone = "0977000116",
                            SchoolId = 7,
                            StudentId = "S00016",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4265)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4268),
                            Email = "student17@example.com",
                            FullName = "Student 17 Fullname",
                            Phone = "0977000117",
                            SchoolId = 8,
                            StudentId = "S00017",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4268)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4271),
                            Email = "student18@example.com",
                            FullName = "Student 18 Fullname",
                            SchoolId = 9,
                            StudentId = "S00018",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4271)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4273),
                            Email = "student19@example.com",
                            FullName = "Student 19 Fullname",
                            Phone = "0977000119",
                            SchoolId = 10,
                            StudentId = "S00019",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4274)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4285),
                            Email = "student20@example.com",
                            FullName = "Student 20 Fullname",
                            Phone = "0977000120",
                            SchoolId = 1,
                            StudentId = "S00020",
                            UpdatedAt = new DateTime(2026, 1, 13, 7, 5, 43, 279, DateTimeKind.Utc).AddTicks(4285)
                        });
                });

            modelBuilder.Entity("SchoolManagement.Models.Student", b =>
                {
                    b.HasOne("SchoolManagement.Models.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchoolManagement.Models.School", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
